version: '2'
services:
  mirakurun:
    build:
        context: mirakurun
    container_name: mirakurun
    privileged: true
    ports:
      - "40772:40772"
    volumes:
     - /etc/localtime:/etc/localtime:ro
     - /mnt/data_01/etc/mirakurun:/usr/local/etc/mirakurun
     - /mnt/data_01/var/db/mirakurun:/usr/local/var/db/mirakurun

  chinachu:
    build:
        context: chinachu
        args:
         - REPOSITORY=git://github.com/Chinachu/Chinachu.git
         - BRANCH=gamma
    container_name: chinachu
    ports:
     - "10772:10772"
     - "20772:20772"
     - "5353:5353/udp"
    volumes:
     - /etc/localtime:/etc/localtime:ro
     - /mnt/data_01/etc/chinachu/config.json:/usr/local/chinachu/config.json
     - /mnt/data_01/etc/chinachu/rules.json:/usr/local/chinachu/rules.json
     - /mnt/data_01/etc/chinachu/data:/usr/local/chinachu/data
     - /mnt/data_01/ts:/usr/local/chinachu/recorded
    links:
     - mirakurun:container-mirakurun
